sudo: required

language: python

services:
  - docker

before_install:
  - docker pull busybox

script:
  - pip install git+https://github.com/rabix/rabix
  - rabix --install https://raw.githubusercontent.com/common-workflow-language/workflows/master/workflows/lobSTR/lobSTR-workflow.cwl

