sudo: required

language: python

services:
  - docker

before_install:
  - docker pull busybox

script:
  - git clone https://github.com/common-workflow-language/common-workflow-language
  - git clone -b feature/tests https://github.com/common-workflow-language/workflows
  - pip install ./common-workflow-language/reference
  - cd workflows/tools
  - python -m cwltool samtools-sort.cwl samtools-sort.inputs.json
